name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - run: yarn --frozen-lockfile
      - run: yarn test
      - run: yarn lint
      - run: yarn run build

      - name: Deploy constants.js
        uses: exuanbo/actions-deploy-gist@v1
        with:
          TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: ./build/src/constants.js
  
      - name: Deploy exec-coordinator-auto-root.js
        uses: exuanbo/actions-deploy-gist@v1
        with:
          TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: ./build/src/exec-coordinator-auto-root.js
  
      - name: Deploy exec-coordinator-hacknet.js
        uses: exuanbo/actions-deploy-gist@v1
        with:
          TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: ./build/src/exec-coordinator-hacknet.js
  
      - name: Deploy exec-coordinator.js
        uses: exuanbo/actions-deploy-gist@v1
        with:
          TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: ./build/src/exec-coordinator.js
  
      - name: Deploy exec-hack.js
        uses: exuanbo/actions-deploy-gist@v1
        with:
          TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: ./build/src/exec-hack.js
  
      - name: Deploy hack-grow.js
        uses: exuanbo/actions-deploy-gist@v1
        with:
          TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: ./build/src/hack-grow.js
  
      - name: Deploy hack-hack.js
        uses: exuanbo/actions-deploy-gist@v1
        with:
          TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: ./build/src/hack-hack.js
  
      - name: Deploy hack-weaken.js
        uses: exuanbo/actions-deploy-gist@v1
        with:
          TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: ./build/src/hack-weaken.js
  
      - name: Deploy lib-auto-root-hosts.js
        uses: exuanbo/actions-deploy-gist@v1
        with:
          TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: ./build/src/lib-auto-root-hosts.js
  
      - name: Deploy lib-discover-hosts.js
        uses: exuanbo/actions-deploy-gist@v1
        with:
          TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: ./build/src/lib-discover-hosts.js
  
      - name: Deploy lib-hack.js
        uses: exuanbo/actions-deploy-gist@v1
        with:
          TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: ./build/src/lib-hack.js
  
      - name: Deploy lib-log.js
        uses: exuanbo/actions-deploy-gist@v1
        with:
          TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: ./build/src/lib-log.js
  
      - name: Deploy lib-print-obj-list.js
        uses: exuanbo/actions-deploy-gist@v1
        with:
          TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: ./build/src/lib-print-obj-list.js
  
      - name: Deploy lib-provision-script.js
        uses: exuanbo/actions-deploy-gist@v1
        with:
          TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: ./build/src/lib-provision-script.js
  
      - name: Deploy lib-shop-nodes.js
        uses: exuanbo/actions-deploy-gist@v1
        with:
          TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: ./build/src/lib-shop-nodes.js
  
      - name: Deploy lib-shop-servers.js
        uses: exuanbo/actions-deploy-gist@v1
        with:
          TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: ./build/src/lib-shop-servers.js
  
      - name: Deploy lib-time.js
        uses: exuanbo/actions-deploy-gist@v1
        with:
          TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: ./build/src/lib-time.js
  