name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - run: yarn --frozen-lockfile
      - run: yarn run compile
  deploy:
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_path: build/exec-list-owned-servers.js
          file_type: text
