name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '19.x'
      - run: yarn --frozen-lockfile
      - run: |
          yarn run build
          echo `ls`
          echo `tree build`
          echo `cat /build/exec-list-owned-servers.js`
          echo "file_content=THIS-IS-A-TEST" >> $GITHUB_ENV
      - run: |
          echo "${{ env.file_content }}"

      - name: Deploy
        uses: sergeysova/gist-write-action@v1      
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          gist_id: 2ca322ffbde25a80c39afb0c1e5cf731
          file_name: exec-list-owned-servers.js
          content: ${{env.file_content}}
